import re

REPORT_PATTERN = re.compile(r'^\s*(?:REPORT|PROGRAM)\s+(\w+)', re.IGNORECASE | re.MULTILINE)
CLASS_DEF_PATTERN = re.compile(r'^\s*CLASS\s+(\w+)\s+DEFINITION', re.IGNORECASE | re.MULTILINE)
CLASS_IMPL_PATTERN = re.compile(r'^\s*CLASS\s+(\w+)\s+IMPLEMENTATION', re.IGNORECASE | re.MULTILINE)
METHOD_PATTERN = re.compile(r'^\s*METHOD\s+(\w+)', re.IGNORECASE | re.MULTILINE)
FUNCTION_PATTERN = re.compile(r'^\s*FUNCTION\s+(\w+)', re.IGNORECASE | re.MULTILINE)
INTERFACE_PATTERN = re.compile(r'^\s*INTERFACE\s+(\w+)', re.IGNORECASE | re.MULTILINE)
FORM_PATTERN = re.compile(r'^\s*FORM\s+(\w+)', re.IGNORECASE | re.MULTILINE)
SELECT_PATTERN = re.compile(r'\bSELECT\b', re.IGNORECASE)
TABLE_PATTERN = re.compile(r'^\s*TABLES\s*:\s*([^.]+)\.', re.IGNORECASE | re.MULTILINE)
AUTH_CHECK_PATTERN = re.compile(r'^\s*AUTHORITY-CHECK\s+OBJECT\s+\'([^\']+)\'', re.IGNORECASE | re.MULTILINE)
CALL_FUNCTION_PATTERN = re.compile(r'^\s*CALL\s+FUNCTION\s+\'([^\']+)\'', re.IGNORECASE | re.MULTILINE)
PARAMETER_PATTERN = re.compile(r'^\s*PARAMETERS\s*:\s*([^.]+)\.', re.IGNORECASE | re.MULTILINE)
SELECT_OPTION_PATTERN = re.compile(r'^\s*SELECT-OPTIONS\s*:\s*([^.]+)\.', re.IGNORECASE | re.MULTILINE)
DATA_PATTERN = re.compile(r'^\s*DATA\s*:\s*([^.]+)\.', re.IGNORECASE | re.MULTILINE)
CONSTANTS_PATTERN = re.compile(r'^\s*CONSTANTS\s*:\s*([^.]+)\.', re.IGNORECASE | re.MULTILINE)
TYPES_PATTERN = re.compile(r'^\s*TYPES\s*:\s*([^.]+)\.', re.IGNORECASE | re.MULTILINE)
ENHANCEMENT_PATTERN = re.compile(r'^\s*ENHANCEMENT\s+(\w+)', re.IGNORECASE | re.MULTILINE)
CDS_VIEW_PATTERN = re.compile(r'^\s*DEFINE\s+VIEW\s+(\w+)', re.IGNORECASE | re.MULTILINE)
RAP_PATTERN = re.compile(r'^\s*DEFINE\s+ROOT\s+VIEW\s+ENTITY\s+(\w+)', re.IGNORECASE | re.MULTILINE)
INCLUDE_PATTERN = re.compile(r'^\s*INCLUDE\s+(\w+)', re.IGNORECASE | re.MULTILINE)
PERFORM_PATTERN = re.compile(r'^\s*PERFORM\s+(\w+)', re.IGNORECASE | re.MULTILINE)
EVENT_PATTERN = re.compile(r'^\s*(INITIALIZATION|START-OF-SELECTION|END-OF-SELECTION|AT SELECTION-SCREEN)', re.IGNORECASE | re.MULTILINE)
